language: php

php:
  - 7.1
  - 7.2

before_script:
  - composer self-update
  - composer install
  - wget https://github.com/php-coveralls/php-coveralls/releases/download/v2.0.0/php-coveralls.phar

script:
  - mkdir -p build/logs
  - composer test
after_script:
  - php php-coveralls.phar -v
